version: "3"

services:
  web:
    build: .
    # image: nginx:alpine
    container_name: nginx_tor
    ports:
      - "2121:4242"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./sshd_config:/etc/ssh/sshd_config
      - ./torrc:/etc/tor/torrc
    environment:
      - TZ=Europe/Berlin
    command: ["sh", "-c", "nginx -g 'daemon off;'"]
    networks:
      - tor_network

  tor:
    image: "dperson/torproxy"
    container_name: tor
    ports:
      - "9050:9050"
    volumes:
      - ./torrc:/etc/tor/torrc
    networks:
      - tor_network

networks:
  tor_network:
    driver: bridge
