services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx_tor
    ports:
      - "2121:4242"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./torrc:/etc/tor/torrc
    networks:
      - tor_network
    restart: on-failure:5

  tor:
    image: "dperson/torproxy"
    container_name: tor
    ports:
      - "9050:9050"
    volumes:
      - ./torrc:/etc/tor/torrc
    networks:
      - tor_network
    restart: on-failure:5

networks:
  tor_network:
    driver: bridge
