services:
  stockholm:
    build:
      context: ./victim
    container_name: stockholm
    ports:
      - 2222:22
    volumes:
      - ./infection:/root/infection
      - ./app:/root/app
      - .env:/root/.env
    env_file:
      - .env
