services:
  stockholm:
    image: python:3.13-alpine
    container_name: stockholm
    volumes:
      - ./infection:/root/infection
      - ./app:/root/app
    env_file:
      - .env
    command: ["tail", "-f"]
